### ISSUE TITLE
ARM64 architecture library for Raspberry pi compute module 4 use

### ISSUE THREAD

**Issue by PierreC081** [gschwind/sg2#3]
Hello @gschwind 

I'm trying to run your python script to get the sun position on a raspberry pi CM4 board as I've succefully done on my windows computer within an ubuntu terminal. 
When entering "pip install sg2 -f https://pip.oie-lab.net/python/", it returns as bellow: 
 

> $ pip install sg2 -f https://pip.oie-lab.net/python/
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Looking in links: https://pip.oie-lab.net/python/
**> ERROR: Could not find a version that satisfies the requirement sg2
> ERROR: No matching distribution found for sg2**

My current python version is 3.9.2

Raspberry CM4 has an ARM64 architecture processor.
Do you think it's a problem to install and use your binary package ?

If yes, would you be able to publish your binary packages compatibles with ARM64? please

Thank you in advance
Best regards

Pierre C.
IMT Mines Albi

**Comment by gschwind** [comment]
Hello,

Currently I didn't made a arm64 binary.

I will consider to make it, but I'm sure there is some issue. I keep you in touch if I have a build that you can try.

Also note that we put binaries on pipy, wich mean that you can use `pip install sg2` now, I will update the main page.

Best regards.

**Comment by PierreC081** [comment]
Hello

Thank you for quick answer

I've tried to use SPA algorithm on the CM4 and python 3.9 and it worked well with available binary packages, in case your binary packages are based on that, it may won't be hard to build ARM64 binaries for SG2 ?! 

Our projet genesis is based on using CM4 for tracking the sun with your algorithm and we would be glad if you or someone make it possible soon :). If it's not in your current schedule/plans, do you know someone from IMT Mines Albi or somebody else that could be interested in helping us to build and compile new binaries packages for Raspberry soon ?

I'm not an IT dev and I really don't know the time that would request.. sorry for my lack of knowledge.

Thank you

Best regards,
Pierre C.

**Comment by gschwind** [comment]
Hello,

I did build a arm64 version (aarch64) that seems to work. Can you tell me if it work for you ?

`pip install sg2 -f https://pip.oie-lab.net/python-devel/`

**Comment by PierreC081** [comment]
Dear Gschwind,

I've just tried it on the CM4 and it works and give same result than on my pc !

Thank you so much! 

Best regards
Pierre
